# Generated by Django 5.0.4 on 2024-05-02 16:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersona',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('pk_persona_curp', models.CharField(db_index=True, max_length=18)),
                ('apellido_paterno', models.CharField(max_length=30, null=True)),
                ('apellido_materno', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('personascol', models.CharField(max_length=45, null=True)),
                ('fk_codigo_postal', models.CharField(max_length=6, null=True)),
                ('calle', models.CharField(max_length=45, null=True)),
                ('numero_exterior', models.CharField(max_length=10, null=True)),
                ('numero_interior', models.CharField(max_length=10, null=True)),
                ('fecha_hora_registro', models.DateTimeField(null=True)),
                ('fk_enum_sexo', models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre')], max_length=6, null=True)),
                ('fk_enum_tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('fk_enum_estado_civil', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)')], max_length=10, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('habla_lengua_indigena', models.BooleanField(null=True)),
                ('cual_lengua_indigena', models.CharField(max_length=45, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fk_cat_asentamiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Catalagos.cat_tipo_asentamientos')),
                ('fk_cat_escolaridad', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Catalagos.cat_escolaridades')),
                ('fk_municipio_nacimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Catalagos.cat_municipios')),
                ('fk_pais_nacimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Catalagos.cat_pais')),
                ('fk_pais_vive', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Catalagos.cat_pais')),
                ('fk_religion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Catalagos.cat_religiones')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('otro_municipio_nacimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Catalagos.cat_municipios')),
            ],
            options={
                'verbose_name': 'historical persona',
                'verbose_name_plural': 'historical personas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk_persona_curp', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('apellido_paterno', models.CharField(max_length=30, null=True)),
                ('apellido_materno', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('personascol', models.CharField(max_length=45, null=True)),
                ('fk_codigo_postal', models.CharField(max_length=6, null=True)),
                ('calle', models.CharField(max_length=45, null=True)),
                ('numero_exterior', models.CharField(max_length=10, null=True)),
                ('numero_interior', models.CharField(max_length=10, null=True)),
                ('fecha_hora_registro', models.DateTimeField(null=True)),
                ('fk_enum_sexo', models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre')], max_length=6, null=True)),
                ('fk_enum_tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('fk_enum_estado_civil', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)')], max_length=10, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('habla_lengua_indigena', models.BooleanField(null=True)),
                ('cual_lengua_indigena', models.CharField(max_length=45, null=True)),
                ('fk_cat_asentamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalagos.cat_tipo_asentamientos')),
                ('fk_cat_escolaridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalagos.cat_escolaridades')),
                ('fk_municipio_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipio_nacimiento_personas', to='Catalagos.cat_municipios')),
                ('fk_pais_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_nacimiento_personas', to='Catalagos.cat_pais')),
                ('fk_pais_vive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_vive_personas', to='Catalagos.cat_pais')),
                ('fk_religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalagos.cat_religiones')),
                ('otro_municipio_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otro_municipio_nacimiento_personas', to='Catalagos.cat_municipios')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
